### ISSUE TITLE
Add isPrivate boolean value in Tuit schema

### ISSUE THREAD

**Issue by laimax17** [laimax17/Tuiter-Team10-node#1]
add a boolean value identify status

**Comment by AliakbarETH** [comment]
There are 2 ways you can use boolean in javascript:

1) You can declare a variable 

let isPrivate = true

2) You can use boolean function 

boolean(isPrivate) // you can check the status of it.

**Comment by laimax17** [comment]
Add isPrivate in tuit model and tuit schema
